"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import logging
import sys
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import urlparse
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"
IS_TESTING = "test" in sys.argv

def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    cleaned: list[str] = []
    for raw in value.split(","):
        v = (raw or "").strip()
        if not v:
            continue
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"', "`"):
            v = v[1:-1].strip()
        if v:
            cleaned.append(v)
    return cleaned

_default_allowed_hosts = [
    "localhost",
    "127.0.0.1",
    "testserver",
    "0.0.0.0",
    "10.0.2.2",
    "10.0.3.2",
    "192.168.1.3",
    "192.168.1.2",
    "172.20.29.202",
    "192.168.55.101",
    "192.168.1.60",
    "192.168.56.1",
]

# Render sets RENDER_EXTERNAL_HOSTNAME for web services
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
ALLOWED_HOSTS = list(dict.fromkeys(_default_allowed_hosts + _split_csv(os.getenv("ALLOWED_HOSTS")) + ([_render_host] if _render_host else [])))

CSRF_TRUSTED_ORIGINS = _split_csv(os.getenv("CSRF_TRUSTED_ORIGINS"))

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --- Admin Email Domain Mode (Production vs Testing) ---
# Toggle accepting non-official email domains (e.g., gmail.com) for testing.
# This MUST remain disabled in production. It can be enabled via environment variable
# ADMIN_EMAIL_TEST_MODE=true only when DEBUG is True.
ADMIN_EMAIL_TEST_MODE = os.getenv('ADMIN_EMAIL_TEST_MODE', 'false').lower() == 'true'

if ADMIN_EMAIL_TEST_MODE and not DEBUG:
    raise RuntimeError("ADMIN_EMAIL_TEST_MODE cannot be enabled when DEBUG=False. Refusing to start.")

if ADMIN_EMAIL_TEST_MODE:
    logging.getLogger(__name__).warning(
        "ADMIN_EMAIL_TEST_MODE is ENABLED: allowing '@gmail.com' for admin registration in development."
    )

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django.contrib.postgres",

    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "corsheaders",
    "channels",
    "channels_redis",
    "redis",

    # Local apps
    "backend.users.apps.UsersConfig",
    "backend.operations.apps.OperationsConfig",
    "backend.analytics.apps.AnalyticsConfig",
    "backend.admin_site.apps.AdminSiteConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "backend.middleware.RequestContextMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip()
if len(DATABASE_URL) >= 2 and DATABASE_URL[0] == DATABASE_URL[-1] and DATABASE_URL[0] in ("'", '"', "`"):
    DATABASE_URL = DATABASE_URL[1:-1].strip()

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "60")),
            ssl_require=not DEBUG,
        )
    }
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
elif IS_TESTING:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    _db_engine = (os.environ.get("DB_ENGINE") or "postgresql").strip().lower()
    if _db_engine in ("sqlite", "sqlite3", "django.db.backends.sqlite3"):
        if not DEBUG:
            raise ImproperlyConfigured(
                "SQLite is not allowed when DJANGO_DEBUG=false. Configure DATABASE_URL for PostgreSQL."
            )

        _db_name = os.environ.get("DB_NAME", "").strip()
        if not _db_name:
            _db_name = str(BASE_DIR / "db.sqlite3")
        elif not os.path.isabs(_db_name):
            _db_name = str(BASE_DIR / _db_name)

        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": _db_name,
            }
        }
    else:
        db_name = (os.environ.get("DB_NAME") or "").strip()
        db_host = (os.environ.get("DB_HOST") or "").strip()
        db_user = (os.environ.get("DB_USER") or "").strip()
        db_port = (os.environ.get("DB_PORT") or "5432").strip()
        db_password = (os.environ.get("DB_PASSWORD") or "").strip()

        if not DEBUG and (not db_name or not db_host or not db_user):
            raise ImproperlyConfigured(
                "PostgreSQL is required. Set DATABASE_URL (recommended) or DB_NAME/DB_HOST/DB_USER."
            )

        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": db_name or "medisync",
                "HOST": db_host or "localhost",
                "PORT": db_port,
                "USER": db_user or "postgres",
                "PASSWORD": db_password,
                "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
                "CONN_HEALTH_CHECKS": True,
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = "/media/"
# Use a temporary directory for development, in production this should be a cloud storage
# like AWS S3, Google Cloud Storage, or similar
import os
MEDIA_ROOT = os.path.join('/tmp', 'medisync_media')

# Ensure the directory exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# File upload settings for enhanced security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644  # Read/write for owner, read for group and others

# Profile picture specific settings
PROFILE_PICTURE_MAX_SIZE = 5 * 1024 * 1024  # 5MB
PROFILE_PICTURE_ALLOWED_FORMATS = ['JPEG', 'PNG', 'WEBP']
PROFILE_PICTURE_MAX_DIMENSIONS = (2000, 2000)  # Max width, height
PROFILE_PICTURE_MIN_DIMENSIONS = (50, 50)  # Min width, height

# Security settings for file uploads
SECURE_FILE_UPLOADS = True
ALLOWED_UPLOAD_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp', '.pdf']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "users.User"

# Admin Site Configuration
ADMIN_SITE_AUTH_USER_MODEL = "admin_site.AdminUser"

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'backend.admin_site.backends.AdminUserBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Django REST Framework Configuration
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Enable JSON, form, and multipart parsers so endpoints like /users/register/
    # can correctly accept FormData with optional file uploads.
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}

# CORS Configuration
# https://github.com/adamchainz/django-cors-headers

_cors_origins = _split_csv(os.getenv("CORS_ALLOWED_ORIGINS"))
CORS_ALLOW_ALL_ORIGINS = DEBUG and not _cors_origins

# Alternative options for different scenarios:

# Option 2: Wildcard pattern (alternative to CORS_ALLOW_ALL_ORIGINS)
# CORS_ALLOWED_ORIGINS = ["*"]

# Option 3: Regex pattern for flexible matching
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https?://.*$",  # Match any http or https origin
#     r"^capacitor://.*$",  # Match any capacitor origin
# ]

# Specific origins (uncomment and customize for production)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:9000",  # Default Quasar dev server port
#     "http://localhost:9001",  # Alternative Quasar dev server port
#     "http://localhost:8080",  # Admin frontend
#     "http://127.0.0.1:9000",
#     "http://127.0.0.1:9001",
#     "http://127.0.0.1:8080",  # Admin frontend
#     "http://192.168.55.101:9000",  # Mobile app development server
#     "http://192.168.55.101:8000",  # Backend API for mobile
#     "capacitor://localhost",  # Capacitor app origin
#     "ionic://localhost",  # Ionic app origin
#     "http://localhost",  # Local development
#     "https://localhost",  # Local development HTTPS
# ]

# Additional CORS settings for development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["x-request-id"]
CORS_EXPOSE_HEADERS = ["X-Request-ID", "X-Response-Time-ms"]
CORS_PREFLIGHT_MAX_AGE = int(os.getenv("CORS_PREFLIGHT_MAX_AGE", "86400"))
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[a-z0-9-]+\.medisync-admin\.pages\.dev$",
    r"^https://[a-z0-9-]+\.medisync-3ip\.pages\.dev$",
    r"^capacitor://localhost$",
    r"^ionic://localhost$",
]
if _cors_origins:
    CORS_ALLOWED_ORIGINS = _cors_origins
elif DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:9000",
        "http://localhost:9001",
        "http://localhost:8080",
        "http://127.0.0.1:9000",
        "http://127.0.0.1:9001",
        "http://127.0.0.1:8080",
        "http://localhost",
        "https://localhost",
    ]
    CORS_ALLOWED_ORIGIN_REGEXES += [
        r"^capacitor://localhost$",
        r"^ionic://localhost$",
    ]

# Allow all methods
CORS_ALLOW_METHODS = [
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Security settings for development
# Allow iframe embedding for media files
X_FRAME_OPTIONS = 'ALLOWALL'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },
    "loggers": {
        "django.request": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "medisync.performance": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "medisync.health": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL, "propagate": False},
    },
}

# Email Backend Configuration
# https://docs.djangoproject.com/en/5.2/topics/email/

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "15"))

def _ensure_url_scheme(value: str) -> str:
    v = (value or "").strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"', "`"):
        v = v[1:-1].strip()
    if not v:
        return v
    if "://" in v:
        return v
    return f"https://{v}"

def _origin_from_url(value: str) -> str:
    v = _ensure_url_scheme(value)
    try:
        p = urlparse(v)
        if not p.scheme or not p.netloc:
            return ""
        return f"{p.scheme}://{p.netloc}"
    except Exception:
        return ""

FRONTEND_URL = _ensure_url_scheme(os.getenv("FRONTEND_URL", "https://medisync-01bi.onrender.com"))
ADMIN_FRONTEND_URL = _ensure_url_scheme(os.getenv("ADMIN_FRONTEND_URL", "https://medisync-admin.pages.dev"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

if not DEBUG:
    if not CSRF_TRUSTED_ORIGINS:
        _trusted = []
        for _u in (FRONTEND_URL, ADMIN_FRONTEND_URL):
            o = _origin_from_url(_u)
            if o and o not in _trusted:
                _trusted.append(o)
        CSRF_TRUSTED_ORIGINS = _trusted

    if not _cors_origins:
        _cors = []
        for _u in (FRONTEND_URL, ADMIN_FRONTEND_URL):
            o = _origin_from_url(_u)
            if o and o not in _cors:
                _cors.append(o)
        if _cors:
            CORS_ALLOWED_ORIGINS = _cors

if DEBUG:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "")
    if not EMAIL_BACKEND:
        if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
            EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
        else:
            EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")

# Celery Configuration
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv("CACHE_URL", REDIS_URL),
    }
}

# Message Encryption Settings
MESSAGE_ENCRYPTION_KEY = os.getenv("MESSAGE_ENCRYPTION_KEY", "development-insecure-key-change-me")

# Channels Configuration for WebSocket
ASGI_APPLICATION = "backend.asgi.application"

# Channel Layers Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

WEBPUSH_VAPID_PUBLIC_KEY = os.getenv("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_SUBJECT = os.getenv("WEBPUSH_VAPID_SUBJECT", "mailto:admin@example.com")
