"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import logging
import sys
import re
from urllib.parse import urlparse, quote
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0").lower() in ["true", "t", "1"]
IS_TESTING = "test" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if IS_TESTING:
        SECRET_KEY = "test-secret-key"
    elif DEBUG:
        SECRET_KEY = "dev-secret-key"
    else:
        raise RuntimeError("SECRET_KEY is required when DEBUG=False.")
_is_render = bool(os.getenv("RENDER_EXTERNAL_HOSTNAME"))

def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    cleaned: list[str] = []
    for raw in re.split(r"[,\s]+", value.strip()):
        v = (raw or "").strip()
        if not v:
            continue
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"', "`"):
            v = v[1:-1].strip()
        if v:
            cleaned.append(v)
    return cleaned

# Render sets RENDER_EXTERNAL_HOSTNAME for web services
#_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
ALLOWED_HOSTS = _split_csv(os.getenv("ALLOWED_HOSTS")) or ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = _split_csv(os.getenv("CSRF_TRUSTED_ORIGINS"))

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ADMIN_EMAIL_TEST_MODE = os.getenv('ADMIN_EMAIL_TEST_MODE', 'false').lower() == 'true'

if ADMIN_EMAIL_TEST_MODE and not DEBUG:
    raise RuntimeError("ADMIN_EMAIL_TEST_MODE cannot be enabled when DEBUG=False. Refusing to start.")

if ADMIN_EMAIL_TEST_MODE:
    logging.getLogger(__name__).warning(
        "ADMIN_EMAIL_TEST_MODE is ENABLED: allowing '@gmail.com' for admin registration in development."
    )

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django.contrib.postgres",

    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "anymail",
    "corsheaders",
    "channels",
    "channels_redis",
    "redis",

    # Local apps
    "backend.users.apps.UsersConfig",
    "backend.operations.apps.OperationsConfig",
    "backend.analytics.apps.AnalyticsConfig",
    "backend.admin_site.apps.AdminSiteConfig",
]

try:
    import rest_framework_simplejwt  # type: ignore
    _simplejwt_available = True
except Exception:
    _simplejwt_available = False

if _simplejwt_available:
    INSTALLED_APPS.insert(INSTALLED_APPS.index("rest_framework.authtoken") + 1, "rest_framework_simplejwt")
elif not IS_TESTING:
    raise RuntimeError("rest_framework_simplejwt is required when not running tests.")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "backend.middleware.RequestContextMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _clean_url_value(value: str | None) -> str:
    v = (value or "").strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"', "`"):
        v = v[1:-1].strip()
    if v.startswith("b'") and v.endswith("'"):
        v = v[2:-1]
    if v.startswith('b"') and v.endswith('"'):
        v = v[2:-1]
    return v.strip()

DATABASE_URL = _clean_url_value(os.getenv("DATABASE_URL"))
DB_NAME = (os.getenv("DB_NAME") or "").strip()
DB_USER = (os.getenv("DB_USER") or "").strip()
DB_PASSWORD = (os.getenv("DB_PASSWORD") or "").strip()
DB_HOST = (os.getenv("DB_HOST") or "").strip()
DB_PORT = (os.getenv("DB_PORT") or "5432").strip()

if IS_TESTING and not DATABASE_URL:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    if not DATABASE_URL:
        missing = [
            k
            for k, v in {
                "DB_NAME": DB_NAME,
                "DB_USER": DB_USER,
                "DB_PASSWORD": DB_PASSWORD,
                "DB_HOST": DB_HOST,
                "DB_PORT": DB_PORT,
            }.items()
            if not v
        ]
        if missing:
            raise RuntimeError(f"Missing required PostgreSQL settings: {', '.join(missing)}")
        DATABASE_URL = (
            "postgresql://"
            f"{quote(DB_USER)}:{quote(DB_PASSWORD)}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
        )

    p = urlparse(DATABASE_URL)
    if p.scheme not in ("postgres", "postgresql"):
        raise RuntimeError("DATABASE_URL must be a PostgreSQL URL (postgres:// or postgresql://).")

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        ),
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = "/media/"
# Use a temporary directory for development, in production this should be a cloud storage
# like AWS S3, Google Cloud Storage, or similar
import os
MEDIA_ROOT = os.path.join('/tmp', 'medisync_media')

# Ensure the directory exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# File upload settings for enhanced security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644  # Read/write for owner, read for group and others

# Profile picture specific settings
PROFILE_PICTURE_MAX_SIZE = 5 * 1024 * 1024  # 5MB
PROFILE_PICTURE_ALLOWED_FORMATS = ['JPEG', 'PNG', 'WEBP']
PROFILE_PICTURE_MAX_DIMENSIONS = (2000, 2000)  # Max width, height
PROFILE_PICTURE_MIN_DIMENSIONS = (50, 50)  # Min width, height

# Security settings for file uploads
SECURE_FILE_UPLOADS = True
ALLOWED_UPLOAD_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp', '.pdf']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "users.User"

# Admin Site Configuration
ADMIN_SITE_AUTH_USER_MODEL = "admin_site.AdminUser"

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'backend.admin_site.backends.AdminUserBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Django REST Framework Configuration
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,  # Returns 20 items per page instead of everything at once
}

if _simplejwt_available:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].insert(
        0, "rest_framework_simplejwt.authentication.JWTAuthentication"
    )

# CORS Configuration
# https://github.com/adamchainz/django-cors-headers

_cors_origins = _split_csv(os.getenv("CORS_ALLOWED_ORIGINS"))
CORS_ALLOW_ALL_ORIGINS = DEBUG and not _cors_origins

# Additional CORS settings for development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["x-request-id"]
CORS_EXPOSE_HEADERS = ["X-Request-ID", "X-Response-Time-ms"]
CORS_PREFLIGHT_MAX_AGE = int(os.getenv("CORS_PREFLIGHT_MAX_AGE", "86400"))
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^capacitor://localhost$",
]
if _cors_origins:
    CORS_ALLOWED_ORIGINS = _cors_origins
elif DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:9000",
        "http://localhost:9001",
        "http://localhost:8080",
        "http://127.0.0.1:9000",
        "http://127.0.0.1:9001",
        "http://127.0.0.1:8080",
        "http://localhost",
        "https://localhost",
        "https://admin-frontend-rouy.onrender.com",
        "https://medisync-frontend-aisj.onrender.com"
    ]
    CORS_ALLOWED_ORIGIN_REGEXES += [
        r"^capacitor://localhost$",
    ]

# Allow all methods
CORS_ALLOW_METHODS = [
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Security settings for development
# Allow iframe embedding for media files
X_FRAME_OPTIONS = 'ALLOWALL'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },
    "loggers": {
        "django.request": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "medisync.performance": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "medisync.health": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL, "propagate": False},
    },
}

# Email Backend Configuration
# https://docs.djangoproject.com/en/5.2/topics/email/

def _ensure_url_scheme(value: str) -> str:
    v = (value or "").strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"', "`"):
        v = v[1:-1].strip()
    if not v:
        return v
    if "://" in v:
        return v
    return f"https://{v}"

def _origin_from_url(value: str) -> str:
    v = _ensure_url_scheme(value)
    try:
        p = urlparse(v)
        if not p.scheme or not p.netloc:
            return ""
        return f"{p.scheme}://{p.netloc}"
    except Exception:
        return ""

def _host_from_url(value: str) -> str:
    v = _ensure_url_scheme(value)
    try:
        p = urlparse(v)
        return str(p.hostname or "").strip()
    except Exception:
        return ""

FRONTEND_URL = _ensure_url_scheme(os.getenv("FRONTEND_URL", "https://medisync-01bi.onrender.com"))
ADMIN_FRONTEND_URL = _ensure_url_scheme(os.getenv("ADMIN_FRONTEND_URL", "https://admin-frontend-rouy.onrender.com"))
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "")
ANYMAIL = {**({"SENDGRID_API_KEY": SENDGRID_API_KEY} if SENDGRID_API_KEY else {})}

_extra_allowed_hosts: list[str] = []
_render_host = str(os.getenv("RENDER_EXTERNAL_HOSTNAME") or "").strip()
if _render_host:
    _extra_allowed_hosts.append(_render_host)
for _u in (FRONTEND_URL, ADMIN_FRONTEND_URL):
    _h = _host_from_url(_u)
    if _h:
        _extra_allowed_hosts.append(_h)
for _h in _extra_allowed_hosts:
    if _h and _h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_h)

if not CSRF_TRUSTED_ORIGINS:
    _trusted = []
    for _u in (FRONTEND_URL, ADMIN_FRONTEND_URL):
        o = _origin_from_url(_u)
        if o and o not in _trusted:
            _trusted.append(o)
    if DEBUG:
        _trusted += ["http://localhost", "http://127.0.0.1", "https://localhost"]
    CSRF_TRUSTED_ORIGINS = _trusted

if not _cors_origins:
    _cors = []
    for _u in (FRONTEND_URL, ADMIN_FRONTEND_URL):
        o = _origin_from_url(_u)
        if o and o not in _cors:
            _cors.append(o)
    if DEBUG:
        _cors += ["http://localhost:9000", "http://localhost:9001", "http://localhost:8080", "http://localhost", "https://localhost"]
    if _cors:
        CORS_ALLOWED_ORIGINS = _cors

EMAIL_DELIVERY_MODE = (os.getenv("EMAIL_DELIVERY_MODE", "") or "").strip().lower() or "sendgrid_api"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "15"))

if EMAIL_DELIVERY_MODE not in ("sendgrid_api", "sendgrid_smtp"):
    raise RuntimeError("EMAIL_DELIVERY_MODE must be 'sendgrid_api' or 'sendgrid_smtp'.")

if EMAIL_DELIVERY_MODE == "sendgrid_smtp":
    if not SENDGRID_API_KEY and (_is_render and not DEBUG):
        raise RuntimeError("SENDGRID_API_KEY is required when EMAIL_DELIVERY_MODE=sendgrid_smtp and DEBUG=False.")
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" if SENDGRID_API_KEY else "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST = "smtp.sendgrid.net"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = "apikey"
    EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
else:
    if SENDGRID_API_KEY:
        EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
    elif DEBUG or not _is_render:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        raise RuntimeError("SENDGRID_API_KEY is required when DEBUG=False.")

if _is_render and not DEFAULT_FROM_EMAIL and not DEBUG and SENDGRID_API_KEY:
    raise RuntimeError("DEFAULT_FROM_EMAIL is required when DEBUG=False.")

# Celery Configuration
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv("CACHE_URL", REDIS_URL),
    }
}

# Message Encryption Settings
MESSAGE_ENCRYPTION_KEY = os.getenv("MESSAGE_ENCRYPTION_KEY", "development-insecure-key-change-me")

# Channels Configuration for WebSocket
ASGI_APPLICATION = "backend.asgi.application"

# Channel Layers Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

WEBPUSH_VAPID_PUBLIC_KEY = os.getenv("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_SUBJECT = os.getenv("WEBPUSH_VAPID_SUBJECT", "mailto:admin@example.com")

QUEUE_NO_SHOW_GRACE_SECONDS = int(os.getenv("QUEUE_NO_SHOW_GRACE_SECONDS", "60") or "60")
QUEUE_NO_SHOW_POLICY = os.getenv("QUEUE_NO_SHOW_POLICY", "move_to_end")
QUEUE_LATE_ARRIVAL_REJOIN_SECONDS = int(os.getenv("QUEUE_LATE_ARRIVAL_REJOIN_SECONDS", "600") or "600")
QUEUE_NO_SHOW_SYNC_V2 = str(os.getenv("QUEUE_NO_SHOW_SYNC_V2", "1") or "1").strip().lower() in ("1", "true", "yes", "y", "on")

SMS_HTTP_URL = os.getenv("SMS_HTTP_URL", "")
SMS_HTTP_TOKEN = os.getenv("SMS_HTTP_TOKEN", "")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
