# Generated by Django 6.0 on 2026-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_site", "0005_alter_adminuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Hospital Logo (PNG, JPG, SVG)",
                null=True,
                upload_to="hospital_logos/",
            ),
        ),
    ]
