# Generated by Django 5.2.5 on 2025-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_merge_20251107_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityqueue',
            name='department',
            field=models.CharField(default='OPD', help_text='Department for which the queue is managed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='queuemanagement',
            name='department',
            field=models.CharField(help_text='Department for which the queue is managed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='queueschedule',
            name='department',
            field=models.CharField(help_text='Department for which the schedule is set', max_length=100),
        ),
        migrations.AlterField(
            model_name='queuestatus',
            name='department',
            field=models.CharField(help_text='Department for which status is tracked', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='queuestatuslog',
            name='department',
            field=models.CharField(help_text='Department for which status changed', max_length=100),
        ),
    ]
