# Generated by Django 6.0 on 2026-01-25 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0032_painassessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        # migrations.RemoveField(
        #     model_name="hospitaldepartmentdoctor",
        #     name="department",
        # ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="doctor",
        ),
        migrations.AlterUniqueTogether(
            name="doctortimeslot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="doctortimeslot",
            name="hospital_department_doctor",
        ),
        migrations.RemoveField(
            model_name="appointmentmanagement",
            name="time_slot",
        ),
        migrations.AlterUniqueTogether(
            name="hospitaldepartmentdoctor",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="hospitaldepartmentdoctor",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="hospitaldepartmentdoctor",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="medicineinventory",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="medicineinventory",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        # migrations.RemoveField(
        #     model_name="messagenotification",
        #     name="message",
        # ),
        # migrations.RemoveField(
        #     model_name="messagereaction",
        #     name="message",
        # ),
        # migrations.RemoveField(
        #     model_name="messagenotification",
        #     name="recipient",
        # ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together=None,
        ),
        # migrations.RemoveField(
        #     model_name="messagereaction",
        #     name="user",
        # ),
        migrations.RemoveField(
            model_name="messaging",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="messaging",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="priorityqueue",
            name="appointment_id",
        ),
        migrations.RemoveField(
            model_name="priorityqueue",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="priorityqueue",
            name="patient",
        ),
        migrations.AlterUniqueTogether(
            name="queueschedule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="queueschedule",
            name="nurse",
        ),
        migrations.RemoveField(
            model_name="queuestatus",
            name="current_schedule",
        ),
        migrations.RemoveField(
            model_name="queuestatus",
            name="last_updated_by",
        ),
        migrations.RemoveField(
            model_name="queuestatuslog",
            name="changed_by",
        ),
        migrations.AlterModelOptions(
            name="painassessment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pain Assessment",
                "verbose_name_plural": "Pain Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="patientassessmentarchive",
            options={
                "ordering": ["-archived_at"],
                "verbose_name": "Patient Assessment Archive",
                "verbose_name_plural": "Patient Assessment Archives",
            },
        ),
        migrations.AlterModelOptions(
            name="queuemanagement",
            options={
                "ordering": ["queue_number"],
                "verbose_name": "Queue Management",
                "verbose_name_plural": "Queue Managements",
            },
        ),
        migrations.RenameField(
            model_name="patientassessmentarchive",
            old_name="created_at",
            new_name="archived_at",
        ),
        migrations.AlterUniqueTogether(
            name="queuemanagement",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="appointmentmanagement",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="appointmentmanagement",
            name="department",
        ),
        migrations.RemoveField(
            model_name="appointmentmanagement",
            name="reschedule_reason",
        ),
        migrations.RemoveField(
            model_name="archiveaccesslog",
            name="record",
        ),
        migrations.RemoveField(
            model_name="patientassessmentarchive",
            name="patient_profile",
        ),
        migrations.RemoveField(
            model_name="patientassessmentarchive",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="painassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientassessmentarchive",
            name="archived_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="painassessment",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Clinical notes regarding the pain assessment",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="painassessment",
            name="pain_score",
            field=models.IntegerField(
                help_text="Pain score from 1 (mild) to 10 (severe)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patientassessmentarchive",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_archives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="queuemanagement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the queue was created."
            ),
        ),
        migrations.AlterField(
            model_name="queuemanagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                help_text="Status of the patient in the queue.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="queuemanagement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the queue was last updated."
            ),
        ),
        migrations.AlterModelTable(
            name="painassessment",
            table="pain_assessments",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="DoctorAvailability",
        ),
        migrations.DeleteModel(
            name="DoctorTimeSlot",
        ),
        migrations.DeleteModel(
            name="HospitalDepartmentDoctor",
        ),
        migrations.DeleteModel(
            name="MedicineInventory",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="MessageNotification",
        ),
        migrations.DeleteModel(
            name="MessageReaction",
        ),
        migrations.DeleteModel(
            name="Messaging",
        ),
        migrations.DeleteModel(
            name="PriorityQueue",
        ),
        migrations.DeleteModel(
            name="QueueSchedule",
        ),
        migrations.DeleteModel(
            name="QueueStatus",
        ),
        migrations.DeleteModel(
            name="QueueStatusLog",
        ),
        migrations.RemoveField(
            model_name="queuemanagement",
            name="dequeue_time",
        ),
        migrations.RemoveField(
            model_name="queuemanagement",
            name="enqueue_time",
        ),
        migrations.RemoveField(
            model_name="queuemanagement",
            name="position_in_queue",
        ),
        migrations.RemoveField(
            model_name="queuemanagement",
            name="started_at",
        ),
    ]
