# Generated by Django 6.0 on 2026-01-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0033_remove_message_conversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveaccesslog",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="operations.patientassessmentarchive",
            ),
        ),
    ]
