# Generated by Django 6.0 on 2026-02-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0034_archiveaccesslog_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuemanagement",
            name="queue_number",
            field=models.PositiveIntegerField(help_text="Queue number (resets daily)"),
        ),
    ]
