# Generated by Django 6.0 on 2026-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0035_alter_queuemanagement_queue_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("OPD", "Out Patient Department"),
                            ("Pharmacy", "Pharmacy"),
                            ("Appointment", "Appointment"),
                        ],
                        help_text="Department for which the daily counter is tracked",
                        max_length=100,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date for the daily sequence counter"),
                ),
                (
                    "current_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Last assigned daily sequence number for this date",
                    ),
                ),
            ],
            options={
                "db_table": "daily_sequence_counters",
                "ordering": ["-date", "department"],
                "unique_together": {("department", "date")},
            },
        ),
    ]
