# Generated by Django 5.2.5 on 2026-03-27 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _ensure_queue_management_columns(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table = "queue_management"
    cols = [
        ("daily_sequence_number", "integer", "INTEGER", "NOT NULL DEFAULT 0"),
        ("dequeue_time", "timestamp with time zone", "DATETIME", "NULL"),
        ("enqueue_time", "timestamp with time zone", "DATETIME", "NOT NULL DEFAULT NOW()"),
        ("position_in_queue", "integer", "INTEGER", "NOT NULL DEFAULT 0"),
        ("started_at", "timestamp with time zone", "DATETIME", "NULL"),
    ]

    def column_exists(column_name: str) -> bool:
        with schema_editor.connection.cursor() as cursor:
            if vendor == "postgresql":
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = CURRENT_SCHEMA()
                      AND table_name = %s
                      AND column_name = %s
                    """,
                    [table, column_name],
                )
                return cursor.fetchone() is not None
            cursor.execute(f"PRAGMA table_info('{table}')")
            rows = cursor.fetchall() or []
            return any(r[1] == column_name for r in rows)

    with schema_editor.connection.cursor() as cursor:
        for name, pg_type, sqlite_type, constraints in cols:
            if column_exists(name):
                continue
            if vendor == "postgresql":
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "{name}" {pg_type} {constraints}'
                )
            else:
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN "{name}" {sqlite_type}'
                )

def _ensure_missing_models(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    def table_exists(table_name: str) -> bool:
        with schema_editor.connection.cursor() as cursor:
            if vendor == "postgresql":
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = CURRENT_SCHEMA()
                      AND table_name = %s
                    """,
                    [table_name],
                )
                return cursor.fetchone() is not None
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name=%s",
                [table_name],
            )
            return cursor.fetchone() is not None

    for model_name in [
        "QueueSchedule",
        "QueueStatus",
        "QueueStatusLog",
        "Conversation",
        "Message",
        "MessageNotification",
        "MessageReaction",
    ]:
        model = apps.get_model("operations", model_name)
        if not table_exists(model._meta.db_table):
            schema_editor.create_model(model)

    conversation = apps.get_model("operations", "Conversation")
    for m2m in getattr(conversation._meta, "local_many_to_many", []):
        through = m2m.remote_field.through
        if not table_exists(through._meta.db_table):
            schema_editor.create_model(through)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_dailysequencecounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='QueueSchedule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('department', models.CharField(help_text='Department for which the schedule is set', max_length=100)),
                        ('start_time', models.TimeField(help_text='Time when queue should open')),
                        ('end_time', models.TimeField(help_text='Time when queue should close')),
                        ('days_of_week', models.JSONField(default=list, help_text='List of days when queue is active (0=Monday, 6=Sunday)')),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                        ('manual_override', models.BooleanField(default=False, help_text='Manual override by nurse (overrides time-based activation)')),
                        ('override_status', models.CharField(choices=[('enabled', 'Manually Enabled'), ('disabled', 'Manually Disabled'), ('auto', 'Automatic')], default='auto', help_text='Current override status', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Queue Schedule',
                        'verbose_name_plural': 'Queue Schedules',
                        'ordering': ['-updated_at'],
                    },
                ),
                migrations.CreateModel(
                    name='QueueStatus',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('department', models.CharField(help_text='Department for which status is tracked', max_length=100, unique=True)),
                        ('is_open', models.BooleanField(default=False, help_text='Whether the queue is currently open for new patients')),
                        ('current_serving', models.PositiveIntegerField(blank=True, help_text='Queue number currently being served', null=True)),
                        ('total_waiting', models.PositiveIntegerField(default=0, help_text='Total number of patients currently waiting')),
                        ('estimated_wait_time', models.DurationField(blank=True, help_text='Estimated wait time for new patients', null=True)),
                        ('status_message', models.CharField(default='Queue Closed', help_text='Current status message displayed to patients', max_length=200)),
                        ('last_updated_at', models.DateTimeField(auto_now=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Queue Status',
                        'verbose_name_plural': 'Queue Statuses',
                    },
                ),
                migrations.CreateModel(
                    name='QueueStatusLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('change_reason', models.CharField(choices=[('schedule', 'Scheduled Time'), ('manual', 'Manual Override'), ('system', 'System Update')], help_text='Reason for status change', max_length=50)),
                        ('department', models.CharField(help_text='Department for which status changed', max_length=100)),
                        ('previous_status', models.BooleanField(help_text='Previous queue open/closed status')),
                        ('new_status', models.BooleanField(help_text='New queue open/closed status')),
                        ('changed_at', models.DateTimeField(auto_now_add=True)),
                        ('additional_notes', models.TextField(blank=True, help_text='Additional notes about the status change')),
                    ],
                    options={
                        'verbose_name': 'Queue Status Log',
                        'verbose_name_plural': 'Queue Status Logs',
                        'ordering': ['-changed_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_queue_management_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='queuemanagement',
                    name='daily_sequence_number',
                    field=models.PositiveIntegerField(default=0, help_text='Sequential number for this patient for the day.'),
                ),
                migrations.AddField(
                    model_name='queuemanagement',
                    name='dequeue_time',
                    field=models.DateTimeField(blank=True, help_text='Timestamp when the patient was removed from the queue.', null=True),
                ),
                migrations.AddField(
                    model_name='queuemanagement',
                    name='enqueue_time',
                    field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the patient was added to the queue.'),
                ),
                migrations.AddField(
                    model_name='queuemanagement',
                    name='position_in_queue',
                    field=models.PositiveIntegerField(default=0, help_text='Position in the queue.'),
                ),
                migrations.AddField(
                    model_name='queuemanagement',
                    name='started_at',
                    field=models.DateTimeField(blank=True, help_text='Timestamp when the queue started.', null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Conversation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Conversation',
                        'verbose_name_plural': 'Conversations',
                        'db_table': 'conversations',
                        'ordering': ['-updated_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Message',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('content', models.TextField(help_text='Encrypted message content.')),
                        ('encrypted_content', models.TextField(blank=True, help_text='Base64 encoded encrypted content')),
                        ('file_attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='message_attachments/')),
                        ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                        ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                        ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                        ('is_delivered', models.BooleanField(default=False, help_text='Whether the message has been delivered')),
                        ('delivered_at', models.DateTimeField(blank=True, help_text='When the message was delivered', null=True)),
                        ('read_at', models.DateTimeField(blank=True, help_text='When the message was read', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent.')),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations.conversation')),
                        ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Message',
                        'verbose_name_plural': 'Messages',
                        'db_table': 'messages',
                        'ordering': ['created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='MessageNotification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('message_delivered', 'Message Delivered'), ('message_read', 'Message Read')], default='new_message', max_length=20)),
                        ('is_sent', models.BooleanField(default=False)),
                        ('sent_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.message')),
                        ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Message Notification',
                        'verbose_name_plural': 'Message Notifications',
                        'db_table': 'message_notifications',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='MessageReaction',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠')], default='like', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='operations.message')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'message_reactions',
                    },
                ),
            ],
        ),
        migrations.RunPython(_ensure_missing_models, reverse_code=migrations.RunPython.noop),
    ]
