# Generated by Django 5.2.5 on 2026-04-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0040_psychiatric_opd_questionnaire"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="psychiatricopdquestionnaire",
            new_name="psychiatric_patient_dd58d3_idx",
            old_name="psychiatric_patient__f7fddb_idx",
        ),
        migrations.RenameIndex(
            model_name="psychiatricopdquestionnaire",
            new_name="psychiatric_updated_0b3860_idx",
            old_name="psychiatric_updated__8d36ea_idx",
        ),
    ]
