# Generated by Django 5.2.5 on 2026-04-14 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0041_rename_psychiatric_patient__f7fddb_idx_psychiatric_patient_dd58d3_idx_and_more",
        ),
        ("users", "0015_remove_patientprofile_hospital_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "permission_change_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=32)),
                ("form_key", models.CharField(max_length=64)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=16)),
                ("allowed", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_access_logs",
                        to="users.patientprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "form_access_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["form_key", "created_at"],
                        name="form_access_form_ke_85b67e_idx",
                    ),
                    models.Index(
                        fields=["allowed", "created_at"],
                        name="form_access_allowed_168593_idx",
                    ),
                ],
            },
        ),
    ]
