# Generated by Django 5.2.5 on 2026-04-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0042_permissionchangelog_formaccesslog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formaccesslog",
            name="patient_profile",
        ),
        migrations.RemoveField(
            model_name="formaccesslog",
            name="user",
        ),
        migrations.DeleteModel(
            name="PermissionChangeLog",
        ),
        migrations.DeleteModel(
            name="FormAccessLog",
        ),
    ]
