# Generated by Django 4.2.7 on 2026-04-28 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0016_patientprofile_patient_id"),
        ("operations", "0044_webpushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAssignmentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_assignment_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="operations.patientassignment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_assignment_audit_logs",
                        to="users.generaldoctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_assignment_audit_logs",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "db_table": "patient_assignment_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="patient_ass_created_7764bf_idx"
                    ),
                    models.Index(
                        fields=["event", "created_at"],
                        name="patient_ass_event_562080_idx",
                    ),
                    models.Index(
                        fields=["assignment", "created_at"],
                        name="patient_ass_assignm_b036b5_idx",
                    ),
                    models.Index(
                        fields=["patient", "created_at"],
                        name="patient_ass_patient_6c9e26_idx",
                    ),
                    models.Index(
                        fields=["doctor", "created_at"],
                        name="patient_ass_doctor__cbfec4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FormAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=32)),
                ("form_key", models.CharField(max_length=64)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=16)),
                ("allowed", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_access_logs",
                        to="operations.patientassignment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_access_logs",
                        to="users.patientprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "form_access_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="form_access_created_258369_idx"
                    ),
                    models.Index(
                        fields=["form_key", "created_at"],
                        name="form_access_form_ke_85b67e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="form_access_user_id_002034_idx",
                    ),
                    models.Index(
                        fields=["patient", "created_at"],
                        name="form_access_patient_31d0cd_idx",
                    ),
                ],
            },
        ),
    ]
