# Generated by Django 6.0.4 on 2026-05-03 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0046_medical_request_documents"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="generatedmedicaldocument",
            new_name="generated_m_doc_typ_bb70a0_idx",
            old_name="gendoc_type_created_idx",
        ),
        migrations.RenameIndex(
            model_name="generatedmedicaldocument",
            new_name="generated_m_patient_9de60f_idx",
            old_name="gendoc_patient_created_idx",
        ),
        migrations.RenameIndex(
            model_name="generatedmedicaldocument",
            new_name="generated_m_doctor__36bbd5_idx",
            old_name="gendoc_doctor_created_idx",
        ),
        migrations.RenameIndex(
            model_name="generatedmedicaldocument",
            new_name="generated_m_documen_34d972_idx",
            old_name="gendoc_docnum_idx",
        ),
        migrations.RenameIndex(
            model_name="medicalrequest",
            new_name="medical_req_patient_79335c_idx",
            old_name="medical_req_patient_created_idx",
        ),
        migrations.RenameIndex(
            model_name="medicalrequest",
            new_name="medical_req_status_c528fc_idx",
            old_name="medical_req_status_created_idx",
        ),
        migrations.AlterField(
            model_name="generatedmedicaldocument",
            name="authenticated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
