# Generated by Django 6.0.4 on 2026-05-07 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0047_rename_gendoc_type_created_idx_generated_m_doc_typ_bb70a0_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecordTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_number", models.CharField(db_index=True, max_length=64)),
                ("file", models.FileField(upload_to="medical_record_transfers/%Y/%m/")),
                ("sha256_hex", models.CharField(blank=True, default="", max_length=64)),
                ("signature_hmac_hex", models.CharField(blank=True, default="", max_length=128)),
                ("encrypted_password", models.TextField(blank=True, default="")),
                ("is_encrypted", models.BooleanField(default=True)),
                (
                    "email_delivery_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("authenticated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.CharField(blank=True, default="", max_length=64)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_record_transfers",
                        to="operations.patientassignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_medical_record_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_transfers",
                        to="users.patientprofile",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_medical_record_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_medical_record_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "medical_record_transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordTransferLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(max_length=64)),
                ("detail", models.TextField(blank=True, default="")),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_record_transfer_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="operations.medicalrecordtransfer",
                    ),
                ),
            ],
            options={
                "db_table": "medical_record_transfer_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransfer",
            index=models.Index(fields=["created_at"], name="medical_rec_created_6b98d6_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransfer",
            index=models.Index(fields=["patient", "created_at"], name="medical_rec_patient_4e2b5a_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransfer",
            index=models.Index(fields=["sender", "created_at"], name="medical_rec_sender__fe92d0_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransfer",
            index=models.Index(fields=["receiver", "created_at"], name="medical_rec_receive_50c00b_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransfer",
            index=models.Index(fields=["document_number"], name="medical_rec_documen_98b5b5_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransfer",
            index=models.Index(fields=["email_delivery_status", "created_at"], name="medical_rec_email_s_b9e127_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransferlog",
            index=models.Index(fields=["created_at"], name="medical_rec_log_crea_e43b3d_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransferlog",
            index=models.Index(fields=["event", "created_at"], name="medical_rec_log_even_8c8e4f_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecordtransferlog",
            index=models.Index(fields=["transfer", "created_at"], name="medical_rec_log_tran_2b93ad_idx"),
        ),
    ]

