# Generated by Django 6.0.4 on 2026-05-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_adminuser_password_reset_fields'),
        ('operations', '0050_appointment_department'),
        ('users', '0016_patientprofile_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when doctor is unavailable')),
                ('reason', models.CharField(blank=True, help_text='Reason for unavailability', max_length=255)),
                ('is_blocked', models.BooleanField(default=True, help_text='Whether the date is blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availability',
                'db_table': 'doctor_availability',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Max number of bookings allowed in this slot')),
                ('booked_count', models.PositiveIntegerField(default=0, help_text='Number of bookings confirmed in this slot')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Time Slot',
                'verbose_name_plural': 'Doctor Time Slots',
                'db_table': 'doctor_time_slot',
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartmentDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('capacity_limit', models.PositiveIntegerField(blank=True, help_text='Optional max concurrent appointments for this mapping.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Department Doctor',
                'verbose_name_plural': 'Hospital Department Doctors',
                'db_table': 'hospital_department_doctor',
            },
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Name of the medicine.', max_length=100)),
                ('stock_number', models.PositiveIntegerField(default=0, help_text='Current stock of the medicine.')),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current available stock of the medicine.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit of the medicine.', max_digits=10)),
                ('minimum_stock_level', models.PositiveIntegerField(default=0, help_text='Minimum stock level before reordering.')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date of the medicine.', null=True)),
                ('batch_number', models.CharField(help_text='Batch number of the medicine.', max_length=50, unique=True)),
                ('last_restocked', models.DateTimeField(auto_now=True, help_text='Last time the medicine was restocked.')),
                ('usage_pattern', models.TextField(blank=True, help_text='Description of the usage pattern for the medicine.')),
            ],
            options={
                'verbose_name': 'Medicine Inventory',
                'verbose_name_plural': 'Medicine Inventory',
                'db_table': 'medicine_inventory',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='PriorityQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('pwd', 'Person With Disability'), ('senior', 'Senior Citizen')], default='senior', help_text='Priority level of the patient in the queue.', max_length=50)),
                ('department', models.CharField(choices=[('OPD', 'Out Patient Department'), ('Billing', 'Billing'), ('Pharmacy', 'Pharmacy'), ('Appointment', 'Appointment')], default='OPD', help_text='Department for which the queue is managed.', max_length=100)),
                ('priority_position', models.PositiveIntegerField(default=0, help_text='Position in the priority queue.')),
                ('skip_normal_queues', models.BooleanField(default=False, help_text='Indicates if the patient should be skipped from the FIFO queue.')),
                ('actual_wait_time', models.DurationField(blank=True, help_text='Actual wait time for the patient.', null=True)),
                ('estimated_wait_time', models.DurationField(blank=True, help_text='Estimated wait time for the patient.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_number', models.PositiveIntegerField(help_text='Queue number for the priority patient.', unique=True)),
            ],
            options={
                'verbose_name': 'Priority Queue',
                'verbose_name_plural': 'Priority Queues',
                'db_table': 'priority_queue',
                'ordering': ['-priority_level', 'priority_position', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransfer',
            new_name='medical_rec_created_42e1fc_idx',
            old_name='medical_rec_created_6b98d6_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransfer',
            new_name='medical_rec_patient_5a234e_idx',
            old_name='medical_rec_patient_4e2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransfer',
            new_name='medical_rec_sender__f1301e_idx',
            old_name='medical_rec_sender__fe92d0_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransfer',
            new_name='medical_rec_receive_2cbe80_idx',
            old_name='medical_rec_receive_50c00b_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransfer',
            new_name='medical_rec_documen_762243_idx',
            old_name='medical_rec_documen_98b5b5_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransfer',
            new_name='medical_rec_email_d_e1f0cf_idx',
            old_name='medical_rec_email_s_b9e127_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransferlog',
            new_name='medical_rec_created_fe7a1a_idx',
            old_name='medical_rec_log_crea_e43b3d_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransferlog',
            new_name='medical_rec_event_c7c5c4_idx',
            old_name='medical_rec_log_even_8c8e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecordtransferlog',
            new_name='medical_rec_transfe_1a85f2_idx',
            old_name='medical_rec_log_tran_2b93ad_idx',
        ),
        migrations.RenameIndex(
            model_name='queuenoshowauditlog',
            new_name='queue_no_sh_created_30fe6c_idx',
            old_name='queue_no_sh_created_4ee7d9_idx',
        ),
        migrations.RenameIndex(
            model_name='queuenoshowauditlog',
            new_name='queue_no_sh_departm_b152c9_idx',
            old_name='queue_no_sh_departm_619cdc_idx',
        ),
        migrations.RenameIndex(
            model_name='queuenoshowauditlog',
            new_name='queue_no_sh_event_4e9263_idx',
            old_name='queue_no_sh_event_7e42fe_idx',
        ),
        migrations.RenameIndex(
            model_name='queuenoshowauditlog',
            new_name='queue_no_sh_patient_9f9039_idx',
            old_name='queue_no_sh_patient_8bd07e_idx',
        ),
        migrations.RenameIndex(
            model_name='queuenoshowauditlog',
            new_name='queue_no_sh_queue_e_eb7535_idx',
            old_name='queue_no_sh_queue_e_9e1c5c_idx',
        ),
        migrations.AddField(
            model_name='appointmentmanagement',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation.', null=True),
        ),
        migrations.AddField(
            model_name='appointmentmanagement',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Reason for rescheduling.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra metadata for the notification (e.g. transfer_id).'),
        ),
        migrations.AlterField(
            model_name='queuemanagement',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='waiting', help_text='Status of the patient in the queue.', max_length=50),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.generaldoctorprofile'),
        ),
        migrations.AddField(
            model_name='appointmentmanagement',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Structured time slot for the appointment (nullable for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='operations.doctortimeslot'),
        ),
        migrations.AddField(
            model_name='hospitaldepartmentdoctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='operations.department'),
        ),
        migrations.AddField(
            model_name='hospitaldepartmentdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='users.generaldoctorprofile'),
        ),
        migrations.AddField(
            model_name='hospitaldepartmentdoctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_doctors', to='admin_site.hospital'),
        ),
        migrations.AddField(
            model_name='doctortimeslot',
            name='hospital_department_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='operations.hospitaldepartmentdoctor'),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='inventory',
            field=models.ForeignKey(limit_choices_to={'user__role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_inventory', to='users.nurseprofile'),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_inventory', to='operations.notification'),
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_queue', to='operations.appointmentmanagement'),
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_queue', to='operations.notification'),
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_queue', to='users.patientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddIndex(
            model_name='hospitaldepartmentdoctor',
            index=models.Index(fields=['hospital', 'department'], name='hospital_de_hospita_cafaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaldepartmentdoctor',
            index=models.Index(fields=['doctor'], name='hospital_de_doctor__7b7c2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitaldepartmentdoctor',
            unique_together={('hospital', 'department', 'doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='doctortimeslot',
            unique_together={('hospital_department_doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
