# Generated by Django 5.2.5 on 2026-05-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0051_department_doctoravailability_doctortimeslot_and_more'),
        ('operations', '0052_notifications_extra_data_sql_safety'),
    ]

    operations = [
    ]
