# Generated by Django 6.0.4 on 2026-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0006_rename_analytics_u_service_1e4b29_idx_uptime_ping_service_85679e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsresult",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("patient_health_trends", "Patient Health Trends"),
                    ("patient_demographics", "Patient Demographics"),
                    ("illness_prediction", "Illness Prediction"),
                    ("medication_analysis", "Medication Analysis"),
                    ("patient_volume_prediction", "Patient Volume Prediction"),
                    ("illness_surge_prediction", "Illness Surge Prediction"),
                    ("weekly_illness_forecast", "Weekly Illness Forecast"),
                    ("monthly_illness_forecast", "Monthly Illness Forecast"),
                    ("problem_checklist", "Problem Checklist Analysis"),
                    ("ai_insights", "AI Insights"),
                    ("full_analysis", "Full Analysis"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analyticstask",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("patient_health_trends", "Patient Health Trends"),
                    ("patient_demographics", "Patient Demographics"),
                    ("illness_prediction", "Illness Prediction"),
                    ("medication_analysis", "Medication Analysis"),
                    ("patient_volume_prediction", "Patient Volume Prediction"),
                    ("illness_surge_prediction", "Illness Surge Prediction"),
                    ("weekly_illness_forecast", "Weekly Illness Forecast"),
                    ("monthly_illness_forecast", "Monthly Illness Forecast"),
                    ("problem_checklist", "Problem Checklist Analysis"),
                    ("ai_insights", "AI Insights"),
                    ("full_analysis", "Full Analysis"),
                ],
                max_length=50,
            ),
        ),
    ]
