# Generated by Django 5.2.5 on 2026-05-15 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_analyticsresult_analysis_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('version', models.IntegerField()),
                ('risk_assessment', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_assessment_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='risk_assess_created_1b98f0_idx'), models.Index(fields=['role'], name='risk_assess_role_2d6d12_idx'), models.Index(fields=['version'], name='risk_assess_version_f444a7_idx')],
            },
        ),
    ]
